version: '3.8'

services:

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - my-network

  nexus:

    image: sonatype/nexus3
    ports:
      - "8081:8081"
    networks:
      - my-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: achatuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  networks:
    my-network:

  volumes:
    mysql-data:
